export const TOKEN_REGISTRY_MODULE_OPTIONS = "TOKEN_REGISTRY_MODULE_OPTIONS";
export const TOKEN_REGISTRY_SERVICE = "TOKEN_REGISTRY_SERVICE";
export const TOKEN_REGISTRY_REDIS = "TOKEN_REGISTRY_REDIS";
